services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
      - 8081:8081
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
